### PR TITLE
CL-7765 Added pay version in getHeader method

### PR DESCRIPTION
**Pull request by tusharpari**
**Purpose:** 
Classy Pay version switch from v1 to v2.

### CODE REVIEW

**Review by timothyk7 — APPROVED** [review]

**Review by timothyk7 — CHANGES_REQUESTED** [review]
can you bump version in package.json

**Comment by tusharpari** [comment]
> can you bump version in package.json



> can you bump version in package.json

@timothyk7 
Currently In package.json, the version is "1.1.4", So you want me to make the version change as 1.1.5 manually?
Or is there any command to generate the version.
Thanks

**Comment by tusharpari** [comment]
> > can you bump version in package.json
> 
> > can you bump version in package.json
> 
> @timothyk7
> Currently In package.json, the version is "1.1.4", So you want me to make the version change as 1.1.5 manually?
> Or is there any command to generate the version.
> Thanks

@timothyk7 
As discussed over a call, I have upgraded the version by one. now its 1.1.5.
Thanks

**Comment by timothyk7** [comment]
closing since can't update

**Comment by antigenius** [comment]
For posterity, the npm repo that this package is published to is owned by someone who no longer works at Classy. We're unable to retrieve the account and, as such, we're preferring ClassyPay Core to Client.

**Pull request closed without merging**
